apiVersion: apps/v1
kind: Deployment
metadata:
  name: dind-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dind
  template:
    metadata:
      labels:
        app: dind
    spec:
      terminationGracePeriodSeconds: 0
      initContainers:
      - name: init-dind
        imagePullPolicy: IfNotPresent
        image: docker:26.1-dind-rootless
        command:
          - sh
          - -c 
          - |
            set -x
            chown 1000:1000 /docker-sock
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: docker-sock
          mountPath: /docker-sock
      containers:
      - name: dind
        image: my-dind:latest
        imagePullPolicy: Never
        args:
          - dockerd
          - --host=unix:///run/docker/docker.sock
        resources:
          requests:
              cpu: 200m
              memory: 300Mi
          limits:
              cpu: 200m
              memory: 2000Mi
              squat.ai/net-tun: 1
        securityContext:
          privileged: false
          runAsUser: 1000
          runAsNonRoot: true
        tty: true
        env:
          - name: DOCKERD_ROOTLESS_ROOTLESSKIT_NET
            value: slirp4netns
#            value: vpnkit
#          - name: DOCKERD_ROOTLESS_ROOTLESSKIT_PORT_DRIVER
#            value: slirp4netns
#          - name: DOCKERD_ROOTLESS_ROOTLESSKIT_SLIRP4NETNS_SECCOMP
#            value: "false"
          - name: DOCKERD_ROOTLESS_ROOTLESSKIT_FLAGS
            value: "--debug"
          - name: DOCKER_ALLOW_IPV6_ON_IPV4_INTERFACE
            value: "1"
#          - name: DOCKER_IPTABLES_LEGACY
#            value: "true"
#          - name: DOCKER_OPTS
#            value: "--cgroup-parent=/kubepods.slice/kubepods-burstable-pod$(POD_UID).slice"
          - name: POD_UID
            valueFrom:
              fieldRef:
                fieldPath: metadata.uid
        volumeMounts:
        - name: docker-sock
          mountPath: /run/docker
      - name: shell
        image: docker:26.1-cli
        command:
          - sleep
          - infinity
        tty: true
        resources:
          requests:
              cpu: 100m
              memory: 100Mi
          limits:
              cpu: 100m
              memory: 100Mi
        env:
          - name: DOCKER_HOST
            value: unix:///run/docker/docker.sock
        volumeMounts:
        - name: docker-sock
          mountPath: /run/docker
      volumes:
      - name: docker-sock
        emptyDir: {}
